module Grapes
  module V1
    class Payments < Grapes::API

      resource :payments do

        # Autor: Jackson Florez Jimenez
        #
        # Fecha creacion: 2021-06-03
        #
        # Autor actualizacion:
        #
        # Fecha actualizacion: 0000-00-00
        #
        # /api/v1/payments
        #
        # Verbo Http: GET
        #
        # Metodo: 
        desc 'Get all payments'
        get do
          Payment.all
          #{ response: "OK", payment: Payment.all}
        end

        # Autor: Jackson Florez Jimenez
        #
        # Fecha creacion: 2021-06-03
        #
        # Autor actualizacion:
        #
        # Fecha actualizacion: 0000-00-00
        #
        # /api/v1/payments/:id
        # /api/v1/payments/1
        #
        # Verbo Http: GET
        #
        # Metodo: 
        desc 'Get one payment'
        params do
          requires :id, type: Integer, desc: 'Payment ID.'
        end
        route_param :id do
          get do
            p = Payment.find(params[:id])
            #{ response: "OK", payment: p}
          rescue ActiveRecord::RecordNotFound
            error!('Payment not found',404)
          end
        end

        # Autor: Jackson Florez Jimenez
        #
        # Fecha creacion: 2021-06-03
        #
        # Autor actualizacion:
        #
        # Fecha actualizacion: 0000-00-00
        #
        # /api/v1/payments
        #
        # Verbo Http: POST
        #
        # Metodo: 
        desc 'Create payment'
        params do
          requires :trip_id, type: Integer, desc: 'Id Trip'
          optional :id_wompi, type: String, desc: 'Id Generated by Wompy'
          optional :amount, type: String, desc: 'Amount transaction'
          optional :status, type: String, desc: 'Status Generated by wompy'
        end
        post do
          p = Payment.create!(declared(params))
          { response: "Successfully created payment!", payment: p}
        end

        # Autor: Jackson Florez Jimenez
        #
        # Fecha creacion: 2021-06-03
        #
        # Autor actualizacion:
        #
        # Fecha actualizacion: 0000-00-00
        #
        # /api/v1/payments/:id
        # /api/v1/payments/1
        #
        # Verbo Http: PUT
        #
        # Metodo: 
        desc 'Update payment'
        params do
          optional :trip_id, type: Integer, desc: 'Id Trip'
          optional :id_wompi, type: String, desc: 'Id Generated by Wompy'
          optional :amount, type: String, desc: 'Amount transaction'
          optional :status, type: String, desc: 'Status Generated by wompy'
        end
        route_param :id do
          put do
            p = Payment.find(params[:id])
            p.update!(declared(params))
            { response: "Successfully updated payment!", payment: p}
          rescue ActiveRecord::RecordNotFound
            error!('Payment not found',404)
          end
        end

        # Autor: Jackson Florez Jimenez
        #
        # Fecha creacion: 2021-06-03
        #
        # Autor actualizacion:
        #
        # Fecha actualizacion: 0000-00-00
        #
        # /api/v1/payments/:id
        # /api/v1/payments/1
        #
        # Verbo Http: DELETE
        #
        # Metodo: 
        desc 'Delete payment'
        params do
          requires :id, type: Integer, desc: 'Payment ID.'
        end
        route_param :id do
          delete do
            Payment.find(params[:id]).delete
            { response: "Successfully deleted payment!"}
          rescue ActiveRecord::RecordNotFound
            error!('Payment not found',404)
          end
        end

      end

    end
  end
end
